# Generated by Django 5.1.7 on 2025-04-15 05:54

import django.core.validators
import django.db.models.deletion
import hr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract')], max_length=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(max_length=50, unique=True)),
                ('leave_code', models.CharField(default=None, max_length=50, unique=True)),
                ('leave_privilege', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid', max_length=20)),
                ('applied_to', models.CharField(default='All', max_length=20)),
                ('effective_after', models.PositiveIntegerField(blank=True, null=True)),
                ('time_unit', models.CharField(blank=True, choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], max_length=10, null=True)),
                ('accrual_enabled', models.BooleanField(default=False)),
                ('leave_time', models.PositiveIntegerField(blank=True, null=True)),
                ('leave_time_unit', models.CharField(blank=True, choices=[('Days', 'Days'), ('Hours', 'Hours')], max_length=10, null=True)),
                ('accrual_frequency', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True)),
                ('count_weekends', models.BooleanField(default=True)),
                ('count_holidays', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('reason', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Reason must be at least 10 characters.'), django.core.validators.MaxLengthValidator(500, 'Reason cannot exceed 500 characters.')])),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png']), hr_app.models.validate_file_size])),
                ('leave_days', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.addemployee')),
            ],
        ),
        migrations.AddField(
            model_name='addemployee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.role'),
        ),
    ]
