# Generated by Django 5.1.7 on 2025-04-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='from_date_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
