# Generated by Django 5.1.7 on 2025-04-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_leave_type_from_date_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
