# Generated by Django 5.1.7 on 2025-03-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='attachment',
        ),
    ]
