# Generated by Django 5.1.7 on 2025-03-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_remove_leaveapplication_attachment'),
    ]

    operations = [
    ]
