# Generated by Django 5.1.7 on 2025-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
