# Generated by Django 5.1.7 on 2025-03-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_addemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
