# Generated by Django 5.1.7 on 2025-03-29 11:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_addemployee_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Reason must be at least 10 characters long.')]),
        ),
    ]
