# Generated by Django 5.1.7 on 2025-04-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate_status',
            field=models.CharField(choices=[('billable', 'Billable'), ('non billable', 'Non Billable')], default='billable', max_length=50),
        ),
    ]
