# Generated by Django 5.1.7 on 2025-03-29 11:16

import django.core.validators
import hr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_alter_leaveapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png']), hr_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Reason must be at least 10 characters.'), django.core.validators.MaxLengthValidator(500, 'Reason cannot exceed 500 characters.')]),
        ),
    ]
