# Generated by Django 5.1.7 on 2025-04-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_project_rate_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
