# Generated by Django 5.1.7 on 2025-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_projects', to='hr_app.addemployee'),
        ),
    ]
