# Generated by Django 5.1.7 on 2025-04-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_role_addemployee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
