# Generated by Django 5.1.7 on 2025-04-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.addemployee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(max_length=50),
        ),
    ]
