# Generated by Django 5.1.7 on 2025-04-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0012_alter_leaveapplication_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='name',
        ),
    ]
