# Generated by Django 5.1.7 on 2025-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0013_remove_leaveapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='available_leaves',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='availed_leaves',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='total_leaves',
            field=models.FloatField(default=12),
        ),
    ]
