# Generated by Django 5.1.7 on 2025-04-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0014_addemployee_available_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20),
        ),
    ]
