# Generated by Django 5.1.7 on 2025-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0015_leaveapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
