# Generated by Django 5.1.7 on 2025-05-12 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0015_employeehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeehistory',
            old_name='emp_identifier',
            new_name='employee_code',
        ),
        migrations.RenameField(
            model_name='employeehistory',
            old_name='record_valid_until',
            new_name='until',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='record_created_at',
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.role'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.addemployee'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10),
        ),
    ]
