# Generated by Django 5.1.7 on 2025-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0016_leaveapplication_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_days',
            field=models.FloatField(default=0),
        ),
    ]
