# Generated by Django 5.1.7 on 2025-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0017_projecthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_projects', to='hr_app.addemployee'),
        ),
    ]
