# Generated by Django 5.1.7 on 2025-05-14 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0018_alter_project_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHandbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Employee Handbook', max_length=255)),
                ('file', models.FileField(upload_to='handbooks/')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHandbookAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.employeehandbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.addemployee')),
            ],
            options={
                'unique_together': {('user', 'handbook')},
            },
        ),
    ]
