# Generated by Django 5.1.7 on 2025-05-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0019_employeehandbook_employeehandbookacknowledgement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeehandbookacknowledgement',
            old_name='user',
            new_name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='employeehandbookacknowledgement',
            unique_together={('employee', 'handbook')},
        ),
    ]
