# Generated by Django 5.1.7 on 2025-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0023_addemployee_is_active_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
