# Generated by Django 5.1.7 on 2025-05-28 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0024_addemployee_failed_login_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='The manager this employee reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to=settings.AUTH_USER_MODEL),
        ),
    ]
