# Generated by Django 5.1.7 on 2025-05-28 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0025_addemployee_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_apply_date', models.DateField(default=django.utils.timezone.now)),
                ('reason_for_resignation', models.TextField()),
                ('expected_last_working_day', models.DateField()),
                ('actual_last_working_day', models.DateField(blank=True, null=True)),
                ('notice_period_months', models.PositiveIntegerField(default=3, help_text='Default notice period in months')),
                ('company_assets_returned', models.BooleanField(default=False, verbose_name='Company Assets Returned (Laptop, ID, etc.)')),
                ('knowledge_transfer_complete', models.BooleanField(default=False, verbose_name='Knowledge Transfer / Handover Complete')),
                ('final_settlement_processed', models.BooleanField(default=False, verbose_name='Final Settlement Processed')),
                ('exit_interview_conducted', models.BooleanField(default=False, verbose_name='Exit Interview Conducted')),
                ('status', models.CharField(choices=[('PENDING_RM_APPROVAL', 'Pending Reporting Manager Approval'), ('PENDING_HR_APPROVAL', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED_BY_RM', 'Rejected by Reporting Manager'), ('REJECTED_BY_HR', 'Rejected by HR'), ('WITHDRAWN', 'Withdrawn by Employee')], default='PENDING_RM_APPROVAL', max_length=50)),
                ('reporting_manager_remarks', models.TextField(blank=True, null=True)),
                ('reporting_manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='hr_app.addemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
