# Generated by Django 5.1.7 on 2025-06-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0028_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#3c8dbc', max_length=20),
        ),
    ]
