# Generated by Django 5.1.7 on 2025-06-04 13:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0029_alter_calendarevent_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_identifier', models.CharField(max_length=100)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('payslip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Salary Data',
                'verbose_name_plural': 'Salary Data',
                'unique_together': {('employee_identifier', 'month', 'year')},
            },
        ),
    ]
