# Generated by Django 5.1.7 on 2025-06-08 09:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0030_salarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydata',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='paid_leaves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='present_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='project_incentive',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='unpaid_leaves',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='variable_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='employee_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='hr_app.addemployee'),
        ),
    ]
