# Generated by Django 5.1.7 on 2025-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0031_salarydata_esi_salarydata_paid_leaves_salarydata_pf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitrequest',
            name='advance_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='any_dues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='bond_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='selected_elsewhere',
            field=models.BooleanField(default=False),
        ),
    ]
