# Generated by Django 5.1.7 on 2025-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0033_exitactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitrequest',
            name='email_subject',
            field=models.CharField(blank=True, help_text='The subject line of the resignation email.', max_length=255, null=True),
        ),
    ]
