# Generated by Django 5.1.7 on 2025-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0036_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('HR Manager', 'HR Manager'), ('HR Executive', 'HR Executive'), ('System Administrator', 'System Administrator'), ('Business Analyst', 'Business Analyst'), ('UI/UX Designer', 'UI/UX Designer')], max_length=100, null=True),
        ),
    ]
