# Generated by Django 5.1.7 on 2025-06-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0038_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_task_messages', to='hr_app.addemployee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_messages', to='hr_app.task')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
